server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
    session:
      cookie:
        name: JSESSIONID

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:49161/xe
    username: 'system'
    password: 'oracle'

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: INFO